force-app/main/default/objects/My_Note__c/My_Note__c.object-meta.xml
<CustomObject>
    <label>My Note</label>
    <nameField>
        <label>Note Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/My_Note__c/fields/Note_Description__c.field-meta.xml
<CustomField>
    <fullName>Note_Description__c</fullName>
    <label>Note Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/NoteTakingController.cls
public without sharing class NoteTakingController {
    public NoteTakingController() {

    }

    @AuraEnabled
    public static boolean createNoteRecord(String title, String description) {
        try {
            if(!String.isBlank(title)) {
                My_Note__c note = new My_Note__c(Name = title, Note_Description__c	= description);
                insert note;
                return true;
            }   
            return false;
        } catch (Exception ex) {
            throw new AuraHandledException('Exception -> ' + ex.getMessage());
        }
    }


    @AuraEnabled(cacheable=true)
    public static List<My_Note__c> getNotes(){
        try {
            List<My_Note__c> noteList = [SELECT ID, Name, Note_Description__c, LastModifiedDate FROM My_Note__c ORDER BY LastModifiedDate DESC];
            return noteList;
        }catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Boolean updateNoteRecord(String title, String description, String noteId) {
        try {
            if(!String.isBlank(noteId)) {
                My_Note__c noteRecord = [SELECT Id, Name, Note_Description__c FROM My_Note__c WHERE Id = :noteId];
                noteRecord.Name = title;
                noteRecord.Note_Description__c = description;
                update noteRecord;
                return true;
            }
            return false;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Boolean deleteNoteRecord(String noteId) {
        try {
            if(!String.isBlank(noteId)) {
                My_Note__c noteRecord = [SELECT Id, Name, Note_Description__c FROM My_Note__c WHERE Id = :noteId];
                delete noteRecord;
                return true;
            }
            return false;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}